### ISSUE TITLE
Get source folder name within custom CSS template

### ISSUE THREAD

**Issue by WhereJuly** [twolfson/gulp.spritesmith#113]
First thanks a lot for the great product!

Sorry to bother you but I looked into the documentation, tried some options, and I did not find how to get a reference to my source folder name from within the custom Mustache template.

The ultimate goal is to be able to insert the source folder name within the CSS class selector name generated by Spritesmith.

The background is that I generate multiple different pairs of `folder.css` + `folder.png` with Spritesmith. I do all the things with Gulp, like reading multiple nested source folders and make the desired output (as per below). The only thing I miss is getting the source folder name into my CSS something like .spriteprefix-`folder`-spritename {CSS rules}. I use `cssOpts.cssSelector` (see below) but I have no effect in my CSS output.

Currently I use this custom Musache template:
```
.sprite {
  background-image: url({{{spritesheet.image}}});
  display: block;
}

{{#sprites}}
.sprite-{{name}} {
  background-position: {{px.offset_x}} {{px.offset_y}};
  width: {{px.width}};
  height: {{px.height}};
}
{{/sprites}}
```

via this Gulp script:
``` javascript
gulp.task('make-sprites', function() {

    // Multiple folders solution taken from here
    // https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md

    var sprite_path = {
        src: 'z_design/images/unprocessed/sprites/src/',
        dest: 'z_design/images/unprocessed/sprites/dest/'
    }

    var folders = getFolders(sprite_path.src);

    var tasks = folders.map(function(folder) {
        gutil.log('Making sprites from folder: ' + folder);
        makeSprites(folder);
    });

    function makeSprites(folder) {
        var spriteData = gulp.src(sprite_path.src + folder + '/**/*.*')
            .pipe(spritesmith({
                algorithm: 'left-right',
                imgName: 'sprites-' + folder + '.png',
                cssName: 'sprites-' + folder + '.css',
                cssTemplate: './spritesmith.tpl.mustache',
                cssOpts: {
                    cssSelector: function(sprite) {
                        return folder + '-' + sprite.name;
                    }
                }
            }))
            .on('error', function(err) {
                console.log(err)
            });
        return spriteData.pipe(gulp.dest(sprite_path.dest));
    }
});

function getFolders(dir) {
    return fs.readdirSync(dir)
        .filter(function(file) {
            return fs.statSync(path.join(dir, file)).isDirectory();
        });
}
```
And I get the following result (excerpt):
``` CSS
.sprite {
  background-image: url(sprites-general.png);
  background-image: url();
  display: block;
}

.sprite-logo-lwr {
  background-position: -95px 0px;
  width: 119px;
  height: 71px;
}
.sprite-main-menu-mark {
  background-position: 0px 0px;
  width: 95px;
  height: 30px;
}
.sprite-vignette-invert-big {
  background-position: -628px 0px;
  width: 210px;
  height: 229px;
}
```

What I want to get is:
- in JS set some Spritesmith parameter equal to my `folder` variable
``` javascript
// some relevant code
 .pipe(spritesmith({
    cssOpts: {
        foldername: folder;
   }
                })...
// the rest of the code
```
- get this parameter within my Mustache template like this
```
{{#sprites}}
.sprite-{{cssOpts.foldername}}-{{name}} {
 // the rest of code here
```
- and get the folder name inserted in my CSS selector name:
``` CSS
.sprite-MYFOLDER-logo-lwr {
  background-position: -95px 0px;
  width: 119px;
  height: 71px;
}
.sprite-MYFOLDER-main-menu-mark {
  background-position: 0px 0px;
  width: 95px;
  height: 30px;
}
// etc
```
I suppose this should be possible with current options. I cannot just find the right one.
Thank you again.
