### ISSUE TITLE
Extract common css

### ISSUE THREAD

**Issue by lordisback** [twolfson/gulp.spritesmith#120]
I want to generate a css file like below: 

```
.icons {
  background-image: url(sprite.png);  
  background-repeat: no-repeat;
  background-size: 100px;
}
.icons-arrow {
  width: 38px;
  height:38px;
  background-position: 0 0; 
}

.icons-up {
  width: 38px;
  height:38px;
  background-position: -38xp -38px; 
}
```

instead of 

```
.icons-arrow {
   background-image: url(sprite.png);  
   background-repeat: no-repeat;
   background-size: 100px;
   width: 38px;
   height:38px;
   background-position: 0 0; 
}
.icons-up {
   background-image: url(sprite.png);  
   background-repeat: no-repeat;
   background-size: 100px;
   width: 38px;
   height:38px;
   background-position: -38xp -38px; 
}
```
what can do?

**Comment by twolfson** [comment]
If you're using `gzip` to serve your CSS, then it will optimize itself automatically:

```bash
# With .icons
$ cat consolidated.css | gzip | wc -c
158

# Without .icons
$ cat unconsolidated.css | gzip | wc -c
155
```

That being said, if you want to consolidate them anyway, then there's a few options:

- Use a custom template or generate non-CSS and define custom classes
- Use a CSS optimizer on the generated CSS (e.g. `csso`)

Here's an example output from CSSO:

```bash
$ csso unconsolidated.txt 
.icons-arrow,.icons-up{background-image:url(sprite.png);background-repeat:no-repeat;background-size:100px;width:38px;height:38px;background-position:0 0}.icons-up{background-position:-38xp -38px}
```

Here's that result beautified:

```css
.icons-arrow, .icons-up {
  background-image: url(sprite.png);
  background-repeat: no-repeat;
  background-size: 100px;
  width: 38px;
  height: 38px;
  background-position: 0 0
}
.icons-up {
  background-position: -38xp -38px
}
```
