### ISSUE TITLE
Conditional templating

### ISSUE THREAD

**Issue by FrancoTanzarella** [twolfson/gulp.spritesmith#139]
I tried a couple of things with my limited knowledge but couldn't get anything to work.

I need to check if an icon has an underscore in its name "foo_bar.png" and if so, use the whole template and if not just use part of it. This is so I can override images in my css in certain conditions.

I want to use the first part of the string before the _ as the first image name (foo) and the last part as the second image name (bar).

My template looks like this

`
{{#sprites}}
.bk-lgo {
    background-image: url({{{escaped_image}}});
    @extend %logo-default;
}

.bk-lgo-{{foo}} {
	background-position: {{px.offset_x}} {{px.offset_y}};
    
    {{#if hasUnderscore}}
        &.bk-lgo-{{bar}} {
	        background-position: {{px.offset_x}} {{px.offset_y}};
        }
    {{/if}}
}
{{/sprites}}
`
As I understand it, I would need some sort of helper in the handlebars template and register that helper in my gulp build. Any help with this would appreciated. Hope this makes sense.

**Comment by FrancoTanzarella** [comment]
Thanks for your reply. A code example would be great, thank you.

**Comment by twolfson** [comment]
Okay, I don't have much time this morning to provide an example. I can't think of how to do the underscore containment in SCSS though I'm sure it's possible

I'd suggest rethinking the approach to instead be that we have 2 lists of sprites which need different classes. So we can use the common `sprites` mixin for all of them then call out the ones that need the additional class explicitly:

```scss
@include sprites($spritesheet-sprites);

@mixin sprite-alt($sprite) {
  .alt-sprite-class {
    background-position: 100px 200px;
  }
}
@include sprite-alt($sprite-foo);
```
