### ISSUE TITLE
Less file compile issue

### ISSUE THREAD

**Issue by meterscao** [twolfson/gulp.spritesmith#148]
Hi, when I use gulp.spritesmith in my project, I found something was wired.

I tried to use `less` as the sprite css output file, but after gulp run `less` task, the sprite file was compiled to empty.

`gulpfile.js`

``` js
var runSpriteTask = function(projectName){
    var sliceSourceFile = projectName + '/slice/*.png';
    var retinaSliceSourceFile = projectName + '/slice/*@2x.png';   

    var spriteData = gulp.src(sliceSourceFile)
                            .pipe(spritesmith({
                                imgName: projectName + '.png',
                                cssName: 'mod-sprite.less',
                                retinaSrcFilter : [retinaSliceSourceFile],
                                retinaImgName: projectName + '@2x.png'
                            }));
    var imgStream = spriteData.img.pipe(gulp.dest(OutputImagePath));
    var cssStream = spriteData.css.pipe(gulp.dest(projectName + '/css/'));
    return merge (imgStream,cssStream)
}
```

And this is gulp.spritesmith export sprite file  `mod-sprite.less`

``` less
/*
LESS variables are information about icon's compiled state, stored under its original file name

.icon-home {
  width: @icon-home-width;
}

The large array-like variables contain all information about a single icon
@icon-home: x y offset_x offset_y width height total_width total_height image_path name;

At the bottom of this section, we provide information about the spritesheet itself
@spritesheet: width height image @spritesheet-sprites;
*/
@approval-detail-reject-name: 'approval_detail_reject';
@approval-detail-reject-x: 0px;
@approval-detail-reject-y: 0px;
@approval-detail-reject-offset-x: 0px;
@approval-detail-reject-offset-y: 0px;
@approval-detail-reject-width: 15px;
@approval-detail-reject-height: 15px;
@approval-detail-reject-total-width: 30px;
@approval-detail-reject-total-height: 15px;
@approval-detail-reject-image: 'worknote-desktop.png';
@approval-detail-reject: 0px 0px 0px 0px 15px 15px 30px 15px 'worknote-desktop.png' 'approval_detail_reject';
@approval-detail-uncheck-name: 'approval_detail_uncheck';
@approval-detail-uncheck-x: 15px;
@approval-detail-uncheck-y: 0px;
@approval-detail-uncheck-offset-x: -15px;
@approval-detail-uncheck-offset-y: 0px;
@approval-detail-uncheck-width: 15px;
@approval-detail-uncheck-height: 15px;
@approval-detail-uncheck-total-width: 30px;
@approval-detail-uncheck-total-height: 15px;
@approval-detail-uncheck-image: 'worknote-desktop.png';
@approval-detail-uncheck: 15px 0px -15px 0px 15px 15px 30px 15px 'worknote-desktop.png' 'approval_detail_uncheck';
@spritesheet-width: 30px;
@spritesheet-height: 15px;
@spritesheet-image: 'worknote-desktop.png';
@spritesheet-sprites: @approval-detail-reject @approval-detail-uncheck;
@spritesheet: 30px 15px 'worknote-desktop.png' @spritesheet-sprites;

/*
The provided classes are intended to be used with the array-like variables

.icon-home {
  .sprite-width(@icon-home);
}
.icon-email {
  .sprite(@icon-email);
}

Example usage in HTML:

`display: block` sprite:
<div class="icon-home"></div>

To change `display` (e.g. `display: inline-block;`), we suggest using a common CSS class:

// CSS
.icon {
  display: inline-block;
}

// HTML
<i class="icon icon-home"></i>
*/
.sprite-width(@sprite) {
  width: extract(@sprite, 5);
}

.sprite-height(@sprite) {
  height: extract(@sprite, 6);
}

.sprite-position(@sprite) {
  @sprite-offset-x: extract(@sprite, 3);
  @sprite-offset-y: extract(@sprite, 4);
  background-position: @sprite-offset-x @sprite-offset-y;
}

.sprite-image(@sprite) {
  @sprite-image: extract(@sprite, 9);
  background-image: e(%('url(%a)', e(@sprite-image)));
}

.sprite(@sprite) {
  .sprite-image(@sprite);
  .sprite-position(@sprite);
  .sprite-width(@sprite);
  .sprite-height(@sprite);
}

/*
The `.sprites` mixin generates identical output to the CSS template
  but can be overridden inside of LESS

This must be run when you have at least 2 sprites.
  If run with a single sprite, then there will be reference errors.

.sprites(@spritesheet-sprites);
*/
.sprites(@sprites, @i: 1) when (@i <= length(@sprites)) {
  @sprite: extract(@sprites, @i);
  @sprite-name: e(extract(@sprite, 10));
  .@{sprite-name} {
    .sprite(@sprite);
  }
  .sprites(@sprites, @i + 1);
}

```

`style-test.less`

``` less
@import "mod-sprite";
body {
    color: red;
    font-size: 20px;
    left: 0;
    top: 0;
}
```

This is compiled file and all the sprite css code were gone.
`style-test.css`

```css
/*
LESS variables are information about icon's compiled state, stored under its original file name

.icon-home {
  width: @icon-home-width;
}

The large array-like variables contain all information about a single icon
@icon-home: x y offset_x offset_y width height total_width total_height image_path name;

At the bottom of this section, we provide information about the spritesheet itself
@spritesheet: width height image @spritesheet-sprites;
*/
/*
These "retina group" variables are mappings for the naming and pairing of normal and retina sprites.

The list formatted variables are intended for mixins like `retina-sprite` and `retina-sprites`.
*/
/*
The provided classes are intended to be used with the array-like variables

.icon-home {
  .sprite-width(@icon-home);
}
.icon-email {
  .sprite(@icon-email);
}

Example usage in HTML:

`display: block` sprite:
<div class="icon-home"></div>

To change `display` (e.g. `display: inline-block;`), we suggest using a common CSS class:

// CSS
.icon {
  display: inline-block;
}

// HTML
<i class="icon icon-home"></i>
*/
/*
The `retina-sprite` class sets up rules and a media query for a sprite/retina sprite.
  It should be used with a "retina group" variable.

The media query is from CSS Tricks: https://css-tricks.com/snippets/css/retina-display-media-query/

@icon-home-group: 'icon-home' @icon-home @icon-home-2x;

.icon-home {
  .retina-sprite(@icon-home-group);
}
*/
/*
The `.sprites` mixin generates identical output to the CSS template
  but can be overridden inside of LESS

This must be run when you have at least 2 sprites.
  If run with a single sprite, then there will be reference errors.

.sprites(@spritesheet-sprites);
*/
/*
The `.retina-sprites` mixin generates a CSS rule and media query for retina groups
  This yields the same output as CSS retina template but can be overridden in LESS

.retina-sprites(@retina-groups);
*/
body {
  color: red;
  font-size: 20px;
  left: 0;
  top: 0;
}
```
