### ISSUE TITLE
Hover effect on icons

### ISSUE THREAD

**Issue by wtfil** [twolfson/gulp.spritesmith#18]
Is it possible to build sprite with `:hover` pseudo-class in css?
For example:

The icon folder contains icons for normal state and hover state:

```
icns
    ├── print.png
    └── print_hover.png
```

gulp task

``` js
var pngSprite = require('gulp.spritesmith');
gulp.task('sprite-png', function () {
    return gulp.src('./icons')
        .pipe(pngSprite({
            imgName: 'sprite.png',
            cssName: 'sprite.css',
            // this is what I want
            hoverImageName: function (name) {
               return name + '_hover';
            }
        }))
        .pipe(gulp.dest('./sprite'));
});

```

I am expecting to see something like this in css file

``` css
.icons-print {                                                                                                                                                                                              
  background-image: url(./sprites/sprite.png);                                                                                                                                                      
  background-position: -734px -618px;                                                                                                                                                                              
  width: 16px;                                                                                                                                                                                                     
  height: 16px;                                                                                                                                                                                                    
}                                                                                                                                                                                                                  
.icns-print:hover {                                                                                                                                                                                           
  background-image: url(./sprites/sprite.png);                                                                                                                                                      
  background-position: -683px -618px;                                                                                                                                                                              
  width: 16px;                                                                                                                                                                                                     
  height: 16px;                                                                                                                                                                                                    
}            
```
